CREATE TABLE IF NOT EXISTS "premier_regard" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"univers" text NOT NULL,
	"first_name" text,
	"last_name" text,
	"email" text,
	"phone" text,
	"company" text,
	"role" text,
	"employees" text,
	"revenue_range" text,
	"remuneration_range" text,
	"seniority_range" text,
	"symptom" text,
	"ambition" text,
	"cost" text,
	"postponed_decision" text,
	"refusal" text,
	"hypotheses" text,
	"contradiction" text,
	"fit" text,
	"cta_chosen" text,
	"email_sent" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'nouveau' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
